### PR TITLE
Manage addresses

### PR DESCRIPTION
**Pull request by Jeremie-Kiwik**
Hello, here is a PR to manage addresses for Companies, Contacts and Individuals.
Hope it was the good way to do it. If not, please guide me on the right direction, I'm willing to help / use your solution.

(And I made a quick fix on Core\Response::json(), which can crash if no 'data' key is returned by the API, for example when you remove an element in Sellsy)

Best regards,
Jérémie,
KIWIK

### CODE REVIEW

**Comment by Jeremie-Kiwik** [comment]
Ah! I read on your README.md that instead of having a whole class dedicated to Addresses, I should add them in `CompaniesApi` and so, like this: 
```php
CompaniesApi::showAddress(...)
```

So do you prefer if I add new methods in existing classes, like this?
```php
CompaniesApi::indexAddress($company, $query)
CompaniesApi::showAddress($company, $id_address, $query)
CompaniesApi::storeAddress($company, $address, $query)
CompaniesApi::updateAddress($company, $address, $query)
CompaniesApi::destroyAddress($company, $id_address)
```

And bonus question: for custom fields, should I do the same?
(https://api.sellsy.com/doc/v2/#operation/update-company-custom-fields)
```php
CompaniesApi::updateCustomFields($company, $array_of_fields)
```

**Comment by tgeorgel** [comment]
Hey @Jeremie-Kiwik !

Thanks a lot for your contribution on this :)

Your work has been released as of [v1.2.4](https://github.com/bluerocktel/sellsy-client/releases/tag/v1.2.4).

Some adjustments I made you might want to know about : 

- Changed the first part of API classes to singular (e.g. `CompanyAdressesApi` vs `CompaniesAdressesApi`) as we are managing multiple addresses of a single entity.
- Make use of Laravel's `Str` helper to avoid `if` statements on the `GenericAddressesApi` constructor.
- Added some helpers on DTO classes to quickly initialize an API class to query addresses, e.g. : 
```php
$contacts = new ContactsApi();
$contact = $contacts->show($contact_id)->entity();

if ($contact) {
    $addresses = $contact->addresses()->index()->entities();
}
```

> I read on your README.md that instead of having a whole class dedicated to Addresses, I should add them in CompaniesApi and so

To be honest, I rather have a distinct class as you did. Otherwise, you would need somehow to give an initiliased Entity to an Api class and it feels weird.

For the Custom Fields, I think this is a pretty common case with Sellsy, and so doing something similar to the Addresses Apis would make cense.

I'm planning to refactorise the Core at some point to better manage relationships, but in the meantime this will do the work.

**Comment by Jeremie-Kiwik** [comment]
A big thanks to have accepted the PR. And the corrections you made make sense.

Just a note: on PHP 7.4, `new GenericAddressesApi()` crash because of:
```php
 __construct(Client|Contact $relatedEntity)
```

(Can't have a '|' in variables types. That's why I choosed to take the bigest parent)
I don't know if you planed to make your code compatible with PHP 7.4, but in doubt...

**Comment by tgeorgel** [comment]
> A big thanks to have accepted the PR. And the corrections you made make sense.
> 
> Just a note: on PHP 7.4, `new GenericAddressesApi()` crash because of:
> 
> ```
>  __construct(Client|Contact $relatedEntity)
> ```
> 
> (Can't have a '|' in variables types. That's why I choosed to take the bigest parent) I don't know if you planed to make your code compatible with PHP 7.4, but in doubt...

Oh damn, I'm so used to PHP 8 that I forgot it was not possible in 7.4 :)

I'm fixing this, I do not want to drop PHP 7 support yet (and even less in a minor version update).

**Comment by tgeorgel** [comment]
Updated tag `v1.2.4`.

**Pull request merged**
