### PR TITLE
Pr fix creditnote endpoint

### PR DESCRIPTION
**Pull request by Jeremie-Kiwik**
For credit-notes, the api endpoint does not match the general rule we edicted in each EntityXxxApi constructor:
```php
$endpoint = Str::of(get_class($relatedEntity))
	->afterLast('\\')
	->lower()
	->plural();
```

This gives `creditnotes` instead of `credit-notes`.

Here is a PR to FIX that problem and give the good API endpoint. I created a new Helper to avoid duplicate the same code on every `EntityXxxApi.php`

This fixes the following calls:
```php
// Get smart tags of a credit-note
$creditNote->smartTags()->index()

// Get custom-fields of a credit-note
$creditNote->customFields()->index()

// Get the favourite filters for credit-notes
$creditNotesApi = new \Bluerock\Sellsy\Api\CreditNotesApi();
$creditNotesApi->favouriteFilters()->index();
```

### CODE REVIEW

**Comment by tgeorgel** [comment]
Hey @Jeremie-Kiwik 

You simply need to convert to kebab case to fix your issue : 

```php
$endpoint = Str::of(get_class($relatedEntity))
	->afterLast('\\')
        ->kebab() // <--- here
	->lower()
	->plural();
```

This can be applied to all routes :)

**Comment by Jeremie-Kiwik** [comment]
ooh I didn't knew that function! Thanks!
So do you prefer to make a quick fix in existing classes, or adding a helper like I did, to try to factorize a little bit?

**Comment by tgeorgel** [comment]
@Jeremie-Kiwik Well, I'm not agains't a helper, however I don't think a class is needed.

We could have a `src/helpers.php` file with the following content : 

```php
namespace Bluerock\Sellsy;

use InvalidArgumentException;
use Illuminate\Support\Str;
use Illuminate\Support\Stringable;
use Bluerock\Sellsy\Api\AbstractApi;
use Bluerock\Sellsy\Entities\Entity;

if (!function_exists('\Bluerock\Sellsy\class_to_endpoint')) :
	/**
	 * Guess the API endpoint from the given API class
	 *
	 * @param AbstractApi | Entity $relatedApi
	 */
	function class_to_endpoint($subject): string
	{
		if (!is_a($subject, AbstractApi::class) && !is_a($subject, Entity::class)) {
			throw new InvalidArgumentException(...);
		}

		$className = get_class($subject);

		return Str::of($className)
			->afterLast('\\')
			->whenEndsWith('Api', fn (Stringable $string) => $string->replaceLast('Api', ''))
			->kebab()
			->lower()
			->plural()
			->toString();
	}
endif;
```

This function would work for both API and Entity classes.

We would need to include the `helpers.php` file in the `composer.json` configuration : 

```json
"autoload": {
    "files": [
        "src/helpers.php"
    ],
    "psr-4": {
        "Bluerock\\Sellsy\\": "src/"
    }
},
```


Then, we could include and use it where needed : 

```php
use function Bluerock\Sellsy\class_to_endpoint;

$this->endpoint = class_to_endpoint($relatedEntity);
```

I think we will need to bump the [illuminate packages](https://github.com/bluerocktel/sellsy-client/blob/main/composer.json#L15-L17) to `>=8.0` to support `whenEndsWith()`.

Finally, do not hesitate to check the [Laravel documentation](https://laravel.com/docs/10.x/strings) about those fluent string helpers, theses are really powerful ! :)

**Comment by tgeorgel** [comment]
Thanks a lot @Jeremie-Kiwik 🙏

**Comment by tgeorgel** [comment]
@Jeremie-Kiwik Released as of `v1.4.0`

**Comment by Jeremie-Kiwik** [comment]
Thanks. You beat me in speed: I just wanted to point out a detail: I didn't use your `->toString()`, and did a "cast as string instead", because `toString()` is only present in `Stringable` for Illuminate 9+. But this would involve dropping PHP 7.4 support.

**Comment by tgeorgel** [comment]
I think the `__toString()` magic method should be present tho— otherwise the `string` cast would not work.
But the cast is a valid solution :)

**Pull request merged**
