### PR TITLE
Manage addresses - V2 using camel case notation

### PR DESCRIPTION
**Pull request by Jeremie-Kiwik**
Here is another try of address management, adding methods to existing APIs, like this:
```php
CompaniesApi::indexAddress($company, $query)
CompaniesApi::showAddress($company, $id_address, $query)
CompaniesApi::storeAddress($company, $address, $query)
CompaniesApi::updateAddress($company, $address, $query)
CompaniesApi::destroyAddress($company, $id_address)
```
I read on your README.md that it was the recommended way of doing, but it was too late I already pushed the 1st PR :'(

### CODE REVIEW

**Comment by Jeremie-Kiwik** [comment]
Closing this PR as the first one does the job :)

**Comment by tgeorgel** [comment]
oops sorry you worked on this, should have commented earlier :')

**Comment by Jeremie-Kiwik** [comment]
No problem :D
While we are at it: I plan to add custom fields management in companies and so . What is your prefered way?
Doing like the addresses, with new classes and use of  Laravel's `Str` helper too?

**Comment by tgeorgel** [comment]
> No problem :D While we are at it: I plan to add custom fields management in companies and so . What is your prefered way? Doing like the addresses, with new classes and use of Laravel's `Str` helper too?

@Jeremie-Kiwik I think It's the better way, yes. 

Most probably a single `CustomFieldsApi` class would be enough.

For the `CustomFieldsApi` class constructor, you could ask for a "HasCustomFields" contract, that you would implement on Entities that actually supports Custom fields : 

```php
// src/Contracts/HasCustomFields.php

namespace Bluerock\Sellsy\Contracts;

interface HasCustomFields {}


// src/Entities/Company.php

use Bluerock\Sellsy\Contracts\HasCustomFields;

class Company extends Client implements HasCustomFields {}


// src/Api/CustomFieldsApi.php

class CustomFieldsApi extends AbstractApi
{
    public function __construct(HasCustomFields $relatedEntity)
}   
```

**Comment by Jeremie-Kiwik** [comment]
In fact, there are 2 kinds of custom fields:
- those which are associated to an entity (ie. /companies/{id}/custom-fields)
- the custom fields declarations in themself (ie. /custom-fields/{id})

For you, should I wrap them all in the same class, with something like this:
```php
$uri = (null === $this->relatedEntity)
	? '/custom-fields'
	: "{$this->endpoint}/{$this->relatedEntity->id}/custom-fields";
```
and having some throwing Exception when called in the wrong context,

Or is it better to split the 2 uses-cases in 2 distinct API, like `CustomFieldsApi` / `EntityCustomFieldsApi` ?

**Comment by Jeremie-Kiwik** [comment]
I think I will go for the 2nd proposition. If I set everything in the same class, half of the code is error detection, of: can I use this method if I have a giben Entity or not. So it is better to split:
- CustomFieldsApi : for managing custom fields in themself
- EntityCustomFieldsApi : for listing custom fields in a given entity

**Comment by tgeorgel** [comment]
> I think I will go for the 2nd proposition. If I set everything in the same class, half of the code is error detection, of: can I use this method if I have a giben Entity or not. So it is better to split:
> 
> * CustomFieldsApi : for managing custom fields in themself
> * EntityCustomFieldsApi : for listing custom fields in a given entity

Yep, much better in two classes IMO. Also, It makes more sense for a future user to understand which class to use depending on the operation he's trying to make.

I'm good with the name `EntityCustomFieldsApi`, but then it would make sense also to change `GenericAddressesApi` for `EntityAddressesApi` to follow the same convention and point it out in the Documentation.

Thanks!

**Pull request closed without merging**
